//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemperatura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class informe
    {
        public int idInforme { get; set; }
        public byte idTipoMedicion { get; set; }
        public System.DateTime fecha { get; set; }
        public float minimo { get; set; }
        public float maximo { get; set; }
        public Nullable<float> promedio { get; set; }
    
        public virtual tipomedicion tipomedicion { get; set; }
    }
}
