//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemperatura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicion
    {
        public long idMedicion { get; set; }
        public byte idTipoMedicion { get; set; }
        public float valor { get; set; }
        public System.DateTime fechaHora { get; set; }
    
        public virtual TipoMedicion TipoMedicion { get; set; }
    }
}
