//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemperatura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoMedicion
    {
        public TipoMedicion()
        {
            this.Informe = new HashSet<Informe>();
            this.Medicion = new HashSet<Medicion>();
        }
    
        public byte idTipoMedicion { get; set; }
        public string tipoMedicion1 { get; set; }
    
        public virtual ICollection<Informe> Informe { get; set; }
        public virtual ICollection<Medicion> Medicion { get; set; }
    }
}
