//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebTemperatura.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipomedicion
    {
        public tipomedicion()
        {
            this.informe = new HashSet<informe>();
            this.medicion = new HashSet<medicion>();
        }
    
        public byte idTipoMedicion { get; set; }
        public string tipoMedicion1 { get; set; }
    
        public virtual ICollection<informe> informe { get; set; }
        public virtual ICollection<medicion> medicion { get; set; }
    }
}
